title: GitNotes
description: A personal knowledge management system
baseurl: "/personal-km"
url: "cbaragao.github.io" # Your GitHub username.github.io
github_username: "cbaragao"
markdown: kramdown

# Theme settings
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

# Just the Docs settings
search_enabled: true
heading_anchors: true
aux_links:
  "View on GitHub":
    - "https://github.com/cbaragao/personal-km"  # Update with your repo URL

# Collections
collections:
  docs:
    output: true
  notes:
    output: true
  resources:
    output: true

# Default values
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
